[*] updated tools - ./.levelup could reload levels now and ./solve checks server connection

diff --git a/home/solve b/home/solve
--- a/home/solve
+++ b/home/solve
@@ -2,6 +2,13 @@
 
 source ./target
 
+./.connection
+if [ $? -ne 0 ]; then
+  echo "Can't verify connection to the TRIX target server!"
+  echo "Make sure, that you've set TRIX server address in $TARGET variable"
+  exit 1
+fi
+
 if [ $# -eq 2  ]; then
 
   solution=$1'-'$2'.solution'
diff --git a/home/status b/home/status
--- a/home/status
+++ b/home/status
@@ -29,3 +29,14 @@ else
 fi
 echo '==============='
 echo ''
+
+# check the connection to server
+./.connection
+if [ $? -ne 0 ]; then
+  echo "Important Message!!!"
+  echo ""
+  echo "Can't verify connection to the TRIX target server!"
+  echo "Make sure, that you've set TRIX server address in TARGET variable"
+  echo ""
+  exit 1
+fi
